### Environment selection
env = qa

### SUT URLs
qa.base.url = https://automationexercise.com/
dev.base.url = https://automationexercise-dev.com/

### Browser Selection
# Browser can be chrome, firefox, webkit, edge
browser = chrome

# headless can be true or false
headless = false

# Allure report config
screenshot.on.pass = false
screenshot.on.fail = true

# Locator Config
test-id= "data-qa"